### ISSUE TITLE
Displaying the two factor code alongside the QR code

### ISSUE THREAD

**Issue by dan-klasson** [jazzband/django-two-factor-auth#242]
Can we pass in the two factor code in the context so we can display this to the user in the template so they can back it up?

https://github.com/Bouke/django-two-factor-auth/blob/master/two_factor/views/core.py#L368

What's the purpose of the backup token functionality when you can just back up the two factor code as is?

**Comment by moggers87** [comment]
It's trivial to override the template to show the shared secret during setup. I do this myself in case a user is unable to scan a QR code (maybe their camera doesn't work, etc.)

Backup tokens are useful because django-two-factor-auth provides more than just a TOTP second factor backend. There's also the SMS, phone, and yubikey backends, none of which have a shared secret to be backed up.

**Comment by Bouke** [comment]
In certain situations I found it useful to have the seed available, besides the QR code. It wouldn't hurt to display the seed alongside the QR code.

**Comment by OmarSRolo** [comment]
I have this problem too, Could somebody  help me?

**Comment by claudep** [comment]
I think this is fixed by #485
