### ISSUE TITLE
Adding translations

### ISSUE THREAD

**Issue by yopiti** [jazzband/django-two-factor-auth#432]
I just translated all German strings. Not sure how to create a pull request from Transiflex. 

Thanks

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser and version:
* Python version:
* Django version:
* django-otp version:
* django-two-factor-auth version:
* Link to your project:

**Comment by gabriel-tessier** [comment]
Just one idea about translation, why not pinning an issue each time some new sentences are added the issue is updated, people who want to translate need to watch the issue. 
Each time new sentences are added the dev update the issue so the translators get a notice and can add their translation.
Check one project that do this:
https://github.com/Zren/plasma-applet-eventcalendar/issues/46

This solution is extremely simple, no dependencies and fast to use for dev and translators.

@yopiti 
There's 13 strings to translate in German (last check 2021-11-15).

Hope it will help removing friction between dev and translator work.

**Comment by claudep** [comment]
Translations from Transifex were fetched in 63714300.
